name: health_api
description: Health api to schedule appointments.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.1
  test: ^1.17.1

